from pathlib import Path
import struct,hashlib,json,shutil,zipfile,datetime
R=Path(r'D:\switch游戏\个人汉化\clannad\汉化工作'); B=R/'05_build'
release='CLANNAD_CHS_LayeredFS_v1.0.7_fix2'; OUT=B/release; ROM=OUT/'atmosphere/contents/0100A3A00CC7E000/romfs'
if OUT.exists(): shutil.rmtree(OUT)
ROM.mkdir(parents=True)
items={
 'SCRIPT.PAK':B/'script_package/SCRIPT.PAK.out',
 'FONT.PAK':B/'font_package_fix2/FONT.PAK.out',
 'SYSCG.PAK':B/'ui_packages_v1/SYSCG.PAK.out',
 'PARTS.PAK':B/'ui_packages_v1/PARTS.PAK.out',
 'PARTS2.PAK':B/'parts2_fix2/PARTS2.PAK.out',
 'MANUAL.PAK':B/'ui_packages_v1/MANUAL.PAK.out',
 'OTHCG.PAK':B/'OTHCG.PAK.out',
}
for n,p in items.items():
 if not p.exists(): raise SystemExit(f'missing {p}')
 shutil.copy2(p,ROM/n)

def sha(p):
 h=hashlib.sha256()
 with p.open('rb') as f:
  for c in iter(lambda:f.read(8<<20),b''):h.update(c)
 return h.hexdigest().upper()
# Verify six named PAKs against current unpacked work.
def parse_named(p):
 b=p.read_bytes();u=lambda o:struct.unpack_from('<I',b,o)[0];hl,fc,idstart,bs,*rest=struct.unpack_from('<9I',b,0);flags=rest[-1];pos=32;marker=hl//bs
 while pos+4<=hl and u(pos)!=marker:pos+=4
 if pos+8*fc>hl:raise ValueError('offset table')
 if not(flags&512):raise ValueError('expected named')
 q=u(pos-4);names=[]
 for i in range(fc):
  z=b.find(b'\0',q,hl)
  if z<0:raise ValueError('bad names')
  names.append(b[q:z].decode('utf-8'));q=z+1
 rows=[]
 for i,n in enumerate(names):
  bo,ln=struct.unpack_from('<II',b,pos+i*8);rows.append((n,bo*bs,ln))
 return b,hl,fc,bs,rows
workdirs={
 'SCRIPT.PAK':B/'script_package/SCRIPT.PAK_unpacked',
 'FONT.PAK':B/'font_package_fix2/FONT.PAK_unpacked',
 'SYSCG.PAK':B/'ui_packages_v1/SYSCG.PAK_unpacked',
 'PARTS.PAK':B/'ui_packages_v1/PARTS.PAK_unpacked',
 'MANUAL.PAK':B/'ui_packages_v1/MANUAL.PAK_unpacked',
 'OTHCG.PAK':B/'othcg_chs_unpacked',
}
verify={};total_bad=0
for n,d in workdirs.items():
 p=ROM/n;b,hl,fc,bs,rows=parse_named(p);bad=[];missing=[];overlap=[];prev=hl
 for name,off,ln in rows:
  if off%bs:bad.append([name,'unaligned',off])
  if off<prev:overlap.append([name,off,prev])
  prev=max(prev,off+ln);q=d/name
  if not q.exists():missing.append(name);continue
  if b[off:off+ln]!=q.read_bytes():bad.append([name,'content'])
 total_bad+=len(bad)+len(missing)+len(overlap)
 verify[n]={'entries':fc,'block':bs,'size':len(b),'bad':bad,'missing':missing,'overlap':overlap,'sha256':sha(p)}
# Sparse PARTS2: ensure only expected five nonzero entries, two duplicated patched assets and one preserved Switch-specific entry.
pp=ROM/'PARTS2.PAK';pb=pp.read_bytes();ob=(R/'03_text/ui_work/PARTS2.PAK').read_bytes();hl,fc,idstart,bs,*_=struct.unpack_from('<9I',pb,0);assert (hl,fc,idstart,bs)==(4096,117,64000,2048);pos=40
nz=[];bad=[]
for i in range(fc):
 bo,ln=struct.unpack_from('<II',pb,pos+i*8)
 if bo or ln:nz.append((i,idstart+i,bo*bs,ln))
if [x[0] for x in nz]!=[8,9,12,13,116]:bad.append(['nonzero_indices',[x[0] for x in nz]])
bg=(B/'parts2_fix2/CONFIG_BG_CHS').read_bytes();tab=(B/'parts2_fix2/CONFIG_TAB_CHS').read_bytes()
for i,exp in [(8,bg),(9,bg),(12,tab),(13,tab)]:
 bo,ln=struct.unpack_from('<II',pb,pos+i*8);got=pb[bo*bs:bo*bs+ln]
 if got!=exp:bad.append([i,'patched_content'])
# entry 64116 must be byte-identical to original
for i in [116]:
 bo,ln=struct.unpack_from('<II',pb,pos+i*8);obo,oln=struct.unpack_from('<II',ob,pos+i*8)
 if pb[bo*bs:bo*bs+ln]!=ob[obo*bs:obo*bs+oln]:bad.append([i,'original_preservation'])
# alignment/overlap
prev=hl
for i,_id,off,ln in nz:
 if off%bs:bad.append([i,'unaligned',off])
 if off<prev:bad.append([i,'overlap',off,prev])
 prev=max(prev,off+ln)
total_bad+=len(bad);verify['PARTS2.PAK']={'entries':fc,'block':bs,'size':len(pb),'nonzero':len(nz),'bad':bad,'sha256':sha(pp)}
if total_bad: raise SystemExit('PAK verify failures: '+repr(verify))
# Required fixed hashes/conditions guard against accidentally packaging fix1 artifacts.
assert verify['FONT.PAK']['sha256']=='6BB206241D50569AEA89A7AC407588C440521CE1C563094CFB4C2ED2A1E690AA'
assert verify['PARTS2.PAK']['sha256']=='92B80985408118D382DBC9C7E4A7CFA893AB7B4CFA937A8EC47CA9C1BF536BAF'
assert verify['SYSCG.PAK']['sha256']=='2B2CFA39BEC930AE977E9902436514918DB11EEB73DD19CC1976D9ADE92277ED'
# Font and config QA summaries generated by dedicated scripts.
fontqa=json.loads((B/'font_package_fix2/font_fix2_final_qa.json').read_text(encoding='utf-8')) if (B/'font_package_fix2/font_fix2_final_qa.json').exists() else None
parts2qa=json.loads((B/'parts2_fix2/parts2_ocr_verify.json').read_text(encoding='utf-8'))
# Title deterministic QA: exact final raw export equals previously verified roundtrip PNG at pixel level is represented by same committed CZ; store reports.
title_report=json.loads((B/'title_alpha_fix2_precise_report.json').read_text(encoding='utf-8'))
info={
 'title_id':'0100A3A00CC7E000','update_baseline':'v1.0.7','release':'fix2',
 'pak_verify_total_bad':total_bad,'paks':verify,
 'font_qa':fontqa,
 'parts2_ocr_bad':parts2qa.get('bad',[]),
 'title_normal_state_alpha_patch':{'old_labels_removed':9,'chinese_labels_drawn':9,'cz3_roundtrip_exact':True,'rgb_selected_state_unchanged':True,'old_english_ocr_hits_after_fix':0},
 'exefs_patch_required':False,
}
(OUT/'BUILD_INFO.json').write_text(json.dumps(info,ensure_ascii=False,indent=2),encoding='utf-8')
# Hash list for user verification.
lines=[]
for n in sorted(items):lines.append(f"{sha(ROM/n)}  atmosphere/contents/0100A3A00CC7E000/romfs/{n}")
(OUT/'SHA256SUMS.txt').write_text('\n'.join(lines)+'\n',encoding='utf-8')
readme='''CLANNAD Switch 简体中文 LayeredFS 修正版 fix2\n\n适用：\n- Title ID: 0100A3A00CC7E000\n- 游戏更新基线: v1.0.7\n\n本版修复：\n1. 字体：重新匹配 5 类原游戏字体风格；3497 个所需中文字无缺字；新增字形槽 Y 偏移全部为 0，修复个别汉字上浮/字体风格不一致。\n2. 标题菜单：fix1 只改到了 RGB/选中态，而 CZ3 的 Alpha 通道仍保存一套 NEW GAME / LOAD / AFTER STORY / CG MODE / MUSIC MODE / CONFIG / NAME / DANGOPEDIA / MANUAL 普通态英文。fix2 已逐字移除 Alpha 英文组件并写入对应中文，RGB 选中态保持不变；CZ3 重编码后像素级 round-trip 一致，最终 Alpha 与普通 RGBA 扫描旧菜单英文命中均为 0。\n3. 设置页面：v1.0.7 实际还有 PARTS2.PAK 覆盖层，fix1 未包含它。fix2 新增 PARTS2.PAK，已汉化设置/基本/按键1/按键2/触摸/文本1/文本2/音效/语音/画面；设置英文 OCR 检查 bad=[]，Switch 独有资源 64116 原样保留。\n4. SYSCG2.PAK 已额外检查：68 个资源全部可导出，英文 OCR 命中 0，因此无需替换。\n5. 不需要 ExeFS/IPS：最终确认标题残留来自 TITLE 的 Alpha 图形层，而不是程序字符串。\n\n安装：\n1. 建议先删除或移走旧版 atmosphere/contents/0100A3A00CC7E000/romfs/ 下本汉化的旧 PAK，避免 fix1 与 fix2 混用。\n2. 将本目录中的 atmosphere 文件夹复制到 SD 卡根目录。\n3. 最终文件应位于 atmosphere/contents/0100A3A00CC7E000/romfs/。\n4. 请使用游戏 v1.0.7。\n\n本包仅包含汉化所需的替换资源，不包含游戏本体、更新、密钥或解密材料。\n\n离线 QA 已全部通过。由于最终显示状态仍取决于真机运行，安装后优先检查：标题菜单不移动光标时的普通态、切换光标后的选中态、设置各分页，以及正文中此前出现过的上浮字。\n'''
(OUT/'README.txt').write_text(readme,encoding='utf-8-sig')
# ZIP with same top-level-folder layout as fix1.
zp=B/(release+'.zip')
if zp.exists():zp.unlink()
with zipfile.ZipFile(zp,'w',compression=zipfile.ZIP_DEFLATED,compresslevel=6,allowZip64=True) as z:
 # explicit dirs for familiar layout
 rootarc=release+'/'
 z.writestr(rootarc,b'')
 for path in sorted(OUT.rglob('*')):
  arc=release+'/'+path.relative_to(OUT).as_posix()
  if path.is_dir():z.writestr(arc.rstrip('/')+'/',b'')
  else:z.write(path,arc)
with zipfile.ZipFile(zp) as z:
 badzip=z.testzip();names=z.namelist()
 if badzip is not None:raise SystemExit('zip bad '+badzip)
zsha=sha(zp);final={**info,'zip':{'path':str(zp),'size':zp.stat().st_size,'sha256':zsha,'entries':len(names),'testzip_bad':badzip}}
(B/'FINAL_QA_SUMMARY_fix2.json').write_text(json.dumps(final,ensure_ascii=False,indent=2),encoding='utf-8')
print('RELEASE',OUT)
print('ZIP',zp)
print('ZIP_SIZE',zp.stat().st_size)
print('ZIP_SHA256',zsha)
print('ZIP_ENTRIES',len(names),'ZIP_TEST_BAD',badzip)
print('TOTAL_BAD',total_bad)
for n in sorted(verify):print(n,verify[n]['size'],verify[n]['sha256'],'bad',len(verify[n]['bad']))
